### PR TITLE
Add support for diff-hl

### PR DESCRIPTION
**Pull request by nyqvist**

### CODE REVIEW

**Comment by alezost** [comment]
Thank you for this addition!

But did you actually check how it looks with this change?  For me, the fringe displays nothing (except small ticks for start/end of modified regions).  This happens because alect themes do not specify background color for `diff` faces, and these `diff-hl` faces should have background, otherwise they are invisible on the fringe.  That's why I ask if it works for you :smile:

So I tried the following settings (with the backgrounds):

```elisp
         (diff-hl-insert ((,c :foreground ,(gc 'fg+1)
                              :background ,(gc 'green-bg))))
         (diff-hl-delete ((,c :inherit diff-hl-insert
                              :background ,(gc 'red-bg))))
         (diff-hl-change ((,c :inherit diff-hl-insert
                              :background ,(gc 'blue-bg))))
```

Is it OK for you?

**Comment by nyqvist** [comment]
Hello!

This is how it looks like for me with the change:
skarmbild_2018-03-12_07-54-02 skarmbild_2018-03-12_07-55-18

I think the dark theme looks good, but with the light one the fringe symbols might be too bright. Is this how it looks for you too?

This is what I get when using your settings from the previous comment:
skarmbild_2018-03-12_08-01-34

So, yes your settings looks better. :) I did not think about the background before.. It is more clear now.

**Comment by alezost** [comment]
> I think the dark theme looks good, but with the light one the fringe
> symbols might be too bright. Is this how it looks for you too?

Not really, but now I see why it looks like this for you.  It's because
you use `diff-hl-margin-mode`, so you get these "+"/"-" symbols
displayed.  This is how a usual `diff-hl-mode` (without
`diff-hl-margin-mode`) looks like:



So as you can see, all you have with the default `diff-hl-mode` is the
background on the fringe.  And your settings didn't provide any
background.  That's why I was surprised by your choice of colors :-)

> So, yes your settings looks better. :) I did not think about the background before.. It is more clear now.

Great!  So I committed it as 69045201a8597181509c71c770d0fbce398f0af5.

Let me know if you think something is not looking good.

(By the way, I don't like how green/blue background colors look like in
the light theme but it's another issue :smile:)

**Comment by nyqvist** [comment]
>  It's because
you use diff-hl-margin-mode, so you get these "+"/"-" symbols
displayed.

Aha, yes you are right.. I should have thought about that :|

Thank you for the fix!

**Pull request closed without merging**
